version: "3"
volumes:
  mongodata:
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      - PORT=3002
      - NODE_ENV=development
    ports:
      - 3002:3002
    volumes:
      - /usr/app/backend/node_modules
      - ./:/usr/app/backend
    depends_on:
      - mongodb
  python-backend:
    build:
      context: ../groupfinda-ai
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
  mongodb:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    restart: always
