version: "3"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      - PORT=3002
      - NODE_ENV=production
    ports:
      - 3002:3002
    volumes:
      - /usr/app/backend/node_modules
      - ./:/usr/app/backend
  python-backend:
    build:
      context: ../groupfinda-ai
      dockerfile: Dockerfile
    ports:
      - 5000:5000
