version: "3"

volumes:
  mongodata:
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      - PORT=3002
      - NODE_ENV=test
    ports:
      - 3002:3002
    volumes:
      - /usr/app/backend/node_modules
      - ./:/usr/app/backend
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    restart: always
  test:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      - PORT=3002
      - NODE_ENV=test
    volumes:
      - /usr/app/backend/node_modules
      - ./:/usr/app/backend
    depends_on:
      - mongodb
      - backend
    command: ./wait-for-it.sh backend:3002 -t 60 -- npm run test
