# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit Tests

on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Building Docker images
        run: docker-compose -f docker-compose-test.yml build
      - name: Run server
        run: docker-compose -f docker-compose-test.yml up -d
      - name: Wait for server to start
        run: sleep 15
      - name: Running tests on Docker
        run: docker-compose -f docker-compose-test.yml run --rm test
      - name: Additional logging output
        if: ${{ failure() }}
        run: docker-compose logs
